### ISSUE TITLE
Doesn't auto-install direnv if asdf is already installed

### ISSUE THREAD

**Issue by chiefy** [redxtech/zsh-asdf-direnv#1]
I have `asdf` installed, but not `direnv` and I get:

```bash
unknown command: direnv. Perhaps you have to reshim?
```

**Comment by iloveitaly** [comment]
I ran into the same issue

**Comment by redxtech** [comment]
I don't use this anymore, but I'd be happy to merge this PR for you!

**Comment by iloveitaly** [comment]
@redxtech that would be great!
